#%RAML 1.0
title: Pruebas con Spreedly
mediaType: 
  - application/json
version: 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/cec62a11-0438-43c3-afb6-ee5e5cf786aa/ # baseUri: core.spreedly.com/v1
 
securitySchemes:
  basic:
    type: Basic Authentication
    displayName: Basic Authentication
    description: Se necesita el usuario y la contraseña para acceder a la petición
protocols:
  [HTTP, HTTPS]
description: Recupere una lista ordenada y paginada de todos los métodos de pago retenidos en el entorno autenticado.
 
documentation:
  - title: API SPREEDLY
    content: obtenemos una lista de gateways https://docs.spreedly.com/reference/api/v1/#list

 
       
/MetodoPago:

  post:
    description: Se obtiene el token del metodo pago

    securedBy:
      - basic
    body: 
      application/json:
        properties:
          input:
            type: !include Archivos/PayMethod.raml
            example: !include Archivos/PayMethod.json
          
    responses: 
      200:
        body: 
          application/json:
            type: !include Archivos/PayMethodOutput.raml
            example: !include Archivos/PayMethodOutput.json


/Compra:
  post:
    description: Se obtiene el token compra, gracias al token de "metodo pago"
    securedBy:
      - basic
    body:
      application/json:
        properties:
          input:
            type:  !include  Archivos/Compra.raml
            example: !include Archivos/Compra.json
    
    responses:
      200:
        body:
          application/json:
            type: !include Archivos/CompraSalida.raml
            example: !include Archivos/CompraSalida.json


/Transaccion:
  description: Con el token de  "compra" podemos ver la transaccion la veces que sea
  post:
    securedBy:
      - basic
    body:
      application/json:
        properties:
          input:
            description: 
            type: !include Archivos/Transaccion.raml
            example: !include Archivos/Transaccion.json
    
    responses:
      200:
        body:
          application/json:
            type: !include Archivos/Transaccion.raml
            example: !include Archivos/TransaccionSalida.json
              
      
