#%RAML 1.0 DataType

type: object
properties: 

 transaction:
  properties:
     payment_method:
       type: string
     amount:
      type: number
  
     currency_code:
      type: string

example: !include Compra.json