#%RAML 1.0 DataType
 
type: object
properties: 
 
  first_name:
     type: string 
  last_name:
     type: string 
  bank_routing_number?:
      type: string  
  bank_account_number?:
      type: string  

 
              
 
example: !include PayMethod.json